[SFT-1058]: Add `freeform/submissions/resave` CLI command
solspace/craft3-freeform pull request #1210
Opened 2024-04-15 09:23 UTC by gustavs-gutmanis

* added `freeform/submissions/resave` CLI command

2024-04-15 18:47 UTC, kjmartens requested changes
This doesn't appear to be working as expected.

Please see [SFT-1060] in Jira

2024-04-25 10:05 UTC, seandelaney commented
@kjmartens @gustavs-gutmanis 

This was the fix: https://github.com/solspace/craft-freeform/pull/1210/files#diff-47d954e1a1cdbee755795a1a08bd594e762880f8cbddba552cbbefb4f0591897R18-R21

Notes service calling `post` in a console request. Resaving submissions all working now.

2024-04-25 10:08 UTC, seandelaney approved these changes

2024-04-29 13:38 UTC, kjmartens approved these changes

2024-04-29 13:38 UTC, merged