fix group hidden problems
solspace/craft3-freeform pull request #1248
Opened 2024-04-30 05:36 UTC by thejahid

2024-04-30 05:43 UTC, gustavs-gutmanis requested changes

2024-04-30 05:43 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-list/implementations/base-fields/base-fields.tsx
> +      {data.groups.grouped?.map(
You should not have changed the front-end at all, all of this logic needs to be in the backend.
You previously returned `hidden` and `groups` in the response, this can still remain exactly like that, just pick the `hidden` fields out of the array in the backend.

2024-04-30 05:46 UTC, thejahid commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout/field-list/implementations/base-fields/base-fields.tsx
> +      {data.groups.grouped?.map(
of course

2024-04-30 06:37 UTC, gustavs-gutmanis requested changes

2024-04-30 06:37 UTC, gustavs-gutmanis commented on packages/plugin/src/controllers/api/fields/GroupsController.php
> +        }
Hmm, what if I have hidden groups set up already? Would this not trigger an error, saying that a record like this already exists?

Also I think using `uid` is not very safe, something might rely on all db rows using `UUID v4`. 

How about using a record with handle `freeform_hidden`?
And before addinga new one, try to fetch one from the db by `FieldTypeGroupRecord::findOne(['handle' => 'freeform_hidden']);`

2024-04-30 08:06 UTC, gustavs-gutmanis submitted a review, later dismissed

2024-05-01 11:52 UTC, gustavs-gutmanis approved these changes

2024-05-01 16:58 UTC, kjmartens approved these changes

2024-05-01 16:58 UTC, merged