fix(SFT-1135): Suppress Craft's minimum password length if we have our own minimum password length setting set
solspace/craft3-freeform pull request #1324
Opened 2024-05-31 19:10 UTC by seandelaney

2024-06-03 09:16 UTC, gustavs-gutmanis requested changes

2024-06-03 09:16 UTC, gustavs-gutmanis commented on packages/plugin/src/Integrations/Elements/User/EventListeners/PasswordTransform.php
> +                */
I guess this is no longer needed?
Should be removed then

2024-06-03 14:27 UTC, gustavs-gutmanis approved these changes

2024-06-05 06:09 UTC, kjmartens approved these changes
Very nice

2024-06-05 06:09 UTC, merged