feat[SFT-1188]: form groups
solspace/craft3-freeform pull request #1493
Opened 2024-08-29 09:57 UTC by thejahid

Ability to group forms for Premium Users.

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/Records/FormGroupsEntriesRecord.php
> +    public const TABLE = '{{%freeform_form_groups_entries}}';
Please use `forms` not `form` here, as in `freeform_forms_groups_entries`

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/Freeform.php
> +                'groups' => GroupsService::class,
Call this `FormGroupsService` otherwise it's not really clear what groups those are

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/Records/FormGroupsRecord.php
>  {
The table name here also needs a plural form `forms`. (e.g. `freeform_forms_groups`)

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/BaseService.php
> +    }
```php
    protected function getFormGroupsService(): FormGroupsService
    {
        return Freeform::getInstance()->formGroups;
    }
```

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/controllers/api/FormsController.php
> +        if ($freeform->edition()->isBelow(Freeform::EDITION_LITE)) {
👌🏻 nice

2024-09-03 12:40 UTC, gustavs-gutmanis commented on packages/plugin/src/controllers/api/GroupsController.php
>  class GroupsController extends BaseApiController
Change this to `FormGroupsController` please

2024-09-03 18:03 UTC, gustavs-gutmanis submitted a review, later dismissed
Great work. One last comment and then we merge

2024-09-03 18:03 UTC, gustavs-gutmanis commented on packages/plugin/src/Bundles/Routing/routes/cp/api.php
> +    'freeform/api/form-groups' => 'freeform/api/form-groups',
change this to `freeform/api/forms/groups` and we're all set with the PR here!
be sure to change the axios call for it too.

2024-09-04 06:07 UTC, gustavs-gutmanis submitted a review, later dismissed

2024-09-12 21:57 UTC, kjmartens requested changes
There are currently a couple of issues to be resolved:

### Form List (Gustavs)
- In List view, Action buttons do not visually work immediately. I am required to refresh the page to see the changes.

### Form Groups (Jahid)
- When the **Freeform Site Filtering** setting is disabled, the Cards view should not care about which site(s) a form is assigned to. All forms should be displayed.
- If feasible, add ability to reorder cards within the main Forms dashboard page, not just inside the Group Manager modal.

2024-09-13 21:01 UTC, kjmartens approved these changes

2024-09-13 23:07 UTC, merged