[SFT-1642]: Initial value of Field isn’t used in Calculation
solspace/craft3-freeform pull request #1676
Opened 2024-12-10 12:05 UTC by thejahid

2024-12-10 13:02 UTC, gustavs-gutmanis submitted a review, later dismissed

2024-12-11 20:25 UTC, kjmartens requested changes
Issues noted in Jira

2024-12-13 15:32 UTC, kjmartens approved these changes

2024-12-13 15:32 UTC, merged

2024-12-13 21:46 UTC, Jimmyawesom reviewed
Thank you I think I'm I don't how things work I mean, there's codes and everything I don't know anything about anything lol

2024-12-21 06:06 UTC, Jimmyawesom commented
> Thank you I think I'm I don't how things work I mean, there's codes and everything I don't know anything about anything lol