[SFT-97]: Property type: option (Manual Entry of Options)
solspace/craft3-freeform pull request #553
Opened 2022-12-15 12:39 UTC by seandelaney

- Added new Options component
- Within Options component exists an Options Editor.
-  Options Editor allows users to select a source (only Custom Options are supported for now) and provides a neat little UI to build a Label/Value list that can be then used within the Select component.

2022-12-16 15:20 UTC, gustavs-gutmanis commented
There is an issue in [AbstractExternalOptionsField.php:77](https://github.com/solspace/craft-freeform/blob/master/packages/plugin/src/Library/Composer/Components/Fields/AbstractExternalOptionsField.php#L57) which comes from the new changes not being supported by the actual field generator. 

Which is perfectly fine, just do a `return []` at the beginning of the method, and continue work, we will get to that part later.

2022-12-16 15:28 UTC, gustavs-gutmanis requested changes
Great work, but leaving a handful of comments to look at.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +  width: 100%;
Please only write rules that are necessary.
I'm not sure about the `padding`, maybe it's required here, but `width` is always 100% for div elements, so that's a redundant rule.
And I'm not sure that `height: 100%` is also necessary here.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +`;
What is the purpose of having it as `display: flex` and setting the item alignment to be that of a generic H3 element, and setting `width` and `height` to 100%, when all of that is out of the box for an H3 element?

We should strive to write as little repetitive code as possible without going nuts, of course, but this seems very redundant and introduces more problems than it solves.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +  justify-content: flex-start;
Margin and padding should be 0 here by default, and width will be 100% by default. Same goes for all the other components I guess.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +export const Table = styled.table`
Nowadays I think `display: grid` is a better tool for displaying tabular data, but if you're not into it, we can skip it for now.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +        }
I would suggest using a classname for this purpose rather than hoping that the element order will always stay the same.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.styles.ts
> +`;
Lots of identical code that has only a thing or two differing.
You could create a base component and then extend them instead.

```suggestion
const BaseIcon = styled.div`
  display: flex;
  vertical-align: middle;
  
  margin: 1px 0 0 0;

  &::after {
    font-weight: 800;
  }
`;

export const DragIcon = styled(BaseIcon)`
  &::after {
    content: '\\2723';
  }
`;

export const DeleteIcon = styled(BaseIcon)`
  &::after {
    content: '\\2715';
  }
`;
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options.tsx
> +  property.label = 'Options Editor';
This should be set in PHP in the `#[Property('Options Editor')` not overridden here in the code.

Otherwise we won't be able to call it whatever we want for some other place which might need different copy.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +  options: OptionProp[] | GenericValue[];
Why can it be both here?
I'm assuming you're entirely responsible for how the data structure ends up being, right?

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +  onChange?: (customOptions: CustomOptionsProps) => void;
This will always be defined, so there's absolutely no necessity for complicating the codebase with `if (onChange)` calls.

```suggestion
  onChange: (customOptions: CustomOptionsProps) => void;
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +    }
```suggestion
    onChange({
      ...value,
      options,
    });
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +    }
```suggestion
```suggestion
    onChange({
      ...value,
      options,
    });
```
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +    let options = JSON.parse(JSON.stringify(value.options));
You should not be doing this `JSON.parse/stringify` hack. We must be able to rely on the original value.
And if we can rely on the original value, then you won't need to define the types of the `.filter()` arguments below, since they will be inferred from the original array.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +      (option: OptionProp, index: number) => index !== optionIndex
```suggestion
      (option, index) => index !== optionIndex
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +   */
Lets not use doctype comments inside of typescript, since everything is already typed.

Also these kinds of comments are more harm than good
```ts
/**
 * Get Specific Item by index
 * @param number index
 */
function getSpecificItem(index: number) {
```

If we're doing or jobs right, the function name should describe what the function is doing, and the function should be doing only one thing.

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +                value.options.map((option: OptionProp, index: number) => (
I think you should be using `options` instead, which already has the correct type and a default value set up.

Also you can type it better and not have to type the `.map()` arguments.
```suggestion
              {options.map((option, index) => (
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +};
This should be a custom hook residing in its own file.

A test for this would also be nice, lets use [@testing-library:keyboard](https://testing-library.com/docs/user-event/keyboard) event tester. 
As well as the [@testing-library/react-hooks](https://react-hooks-testing-library.com/usage/basic-hooks) for testing hooks

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/options-editor.tsx
> +  source: string;
This should be an `enum` instead

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/options-editor.tsx
> +  onChange?: (value: OptionsEditorProps) => void;
Also no need to make it optional

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/options-editor.tsx
> +      {value.source == 'customOptions' && (
When we would have them as enums, we would check for it here using enums as well.

```ts
value.source === Source.CustomOptions
```

2022-12-16 15:28 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/options-editor.tsx
> +          value={(value.customOptions as CustomOptionsProps) || []}
This should already be typed before it comes here.
`value` should reflect all of the values it will contain.
This will never change and is known to us beforehand.

2022-12-19 14:04 UTC, seandelaney commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +      (option: OptionProp, index: number) => index !== optionIndex
@gustavs-gutmanis Typescript complains if I remove `OptionProp` and `number` here.

2022-12-19 14:54 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor/custom-options.tsx
> +      (option: OptionProp, index: number) => index !== optionIndex
Yes, because of `let options = JSON.parse(JSON.stringify(value.options));` the `options` variable is of type `any`, thus the `.filter` method cannot infer anything.

The solution should be typing the `value` property, so that typescript knows it contains `options` and that they are of type `OptionProp[]`. That would solve this problem

2022-12-21 13:13 UTC, gustavs-gutmanis approved these changes
Beautiful work @seandelaney 

I added two more files to split out the logic a bit for the custom checkboxes. Please take a look at it and let me know what you think.

2022-12-21 13:13 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor.styles.ts
> +  width: 100%;
I really doubt that `width: 100%` is needed here and for the others as well, width is automatically 100% for all block elements.

2022-12-21 14:08 UTC, seandelaney commented on packages/client/src/app/pages/forms/edit/builder/tabs/layout-editor/property-editor/form-controls/options-editor.styles.ts
> +  width: 100%;
It's needed. I removed it and the layout broke on me.

2022-12-21 15:31 UTC, merged