fix(SFT-700): revised diagnostics page
solspace/craft3-freeform pull request #939
Opened 2023-12-13 17:48 UTC by thejahid

Freeform includes a self-diagnostics page that may help customers track down potential issues with their setup and allow them to easily share diagnostic results with the software Support team to assist them faster.

2023-12-14 08:38 UTC, gustavs-gutmanis requested changes
Great job.
Please see my comments, there's a couple of things that I fixed, and there's a couple that I left for you to fix.

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Library/DataObjects/Summary/Statistics/Spam.php
> +    public $bypassSpamCheckOnLoggedInUsers = false;
If you notice any places where the property type isn't defined - it's very welcome to specify them.

```suggestion
    public bool $bypassSpamCheckOnLoggedInUsers = false;
```

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +    public function getFreeformIntegrations()
Lets strive to always define return types of functions.

```suggestion
    /**
     * @return DiagnosticItem[]
     */
    public function getFreeformIntegrations(): array
```

In this case, we would also need a @DocType since the `array` return type doesn't encompass the type of elements inside the array. Otherwise the @DocType is unnecessary.

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +            $version = isset($integration['version']) && '' !== $integration['version'] ? "({$integration['version']})" : '';
Rule of thumb here would be to always define a variable when having to lookup and use an array key more than once.

But in this case, you can just define the variable once, and then modify itself if the value is present;

Also, there's no need to do a `'' !==` check, since it will either be empty or it won't.

```suggestion
            $version = $integration['version'];
            $version = $version ? "({$version})" : ''
```

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +            $plural = 1 != $count ? 's' : '';
I'm not 100% sure, we can wait for @kjmartens input, but I think there's no benefit for us to use plurals at all here, because translating it into different languages might not work with plurals, since some languages have a vastly different approach to plurals.

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +        ;
Personally I think having full table name aliases make the queries less readable, rather than more readable.

So aliasing tables with initials I think makes more sense.

Instead of `forms_integrations.id` using `fi.id`

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +                ];
Since we're using that huge path of a parameter more than once, it makes for cleaner code to extract it into a variable.

```suggestion
                $type = $this->integrationTypeProvider->getTypeDefinition($integration['class']);
                $integrationsByForm[$id] = [
                    'name' => $type->name,
                    'version' => $type->version,
                    'count' => 0,
                ];
```

And then, to prevent the `version` from being `null`, we can default it to an empty string.


```
$type = $this->integrationTypeProvider->getTypeDefinition($integration['class']);
$integrationsByForm[$id] = [
    'name' => $type->name,
    'version' => $type->version ?? '',
    'count' => 0,
];
```

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/Form/FieldsService.php
> +    }
This makes sense here 👍🏻

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/Form/FieldsService.php
> +    }
This doesn't make sense here.

First of all, this is very Stripe centric, meaning that only the Stripe  integration should be handling this logic, since Freeform should know nothing about this otherwise.

But for posterity - since it will only be used in the diagnostics page, we can have this logic inside the Diagnostics Service.

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/FormsService.php
> +    }
I would modify this to broaden the use case.
Expose the method for fetching form ID's but let the dev specify a `$type` if they want, which will then modify the query to filter out a specific type.

Then in the place where you use this, pass in the `Regular::class` as the function argument.

```suggestion
    public function getAllFormIds(?string $type = null): array
    {
        $query = $this>getFormQuery()>select('id');
        if (null !== $type) {
            $query->where(['type' => $type]);
        }
        
        return $query->column();
    }
```

2023-12-14 08:38 UTC, gustavs-gutmanis commented on packages/plugin/src/templates/settings/_diagnostics.twig
I have made several changes to the template to make it more readable and have less conditionals in it.

Templates should try to have as little logic inside them as possible, so I moved the checks out into the `DiagnosticItem` object instead, to make rendering templates easier and cleaner. Please see the changes I've made.

2023-12-14 12:18 UTC, thejahid commented on packages/plugin/src/templates/settings/_diagnostics.twig
There is a {{ key }} that prints the array key, such as 1, 2, 3. Do we need to retain it in the HTML and apply something like 'sr-only' as in Tailwind?

2023-12-14 12:26 UTC, gustavs-gutmanis commented on packages/plugin/src/templates/settings/_diagnostics.twig
I don't think we need it. I see you already removed it, so that's good.

2023-12-14 14:14 UTC, kjmartens requested changes
Just noticing a couple minor issues:

1. When both conditions apply for the Memory Limit, just the warning one should show, not both. So I guess the blue suggestion conditional might work better if it only shows when the memory limit is between 256M-511M (rather than below 512M).
<img width="673" alt="Screenshot 2023-12-14 at 8 05 01 AM" src="https://github.com/solspace/craft-freeform/assets/1821674/715b51ae-4475-4ed1-b8c8-fe7eb3114bcb">

2. The version numbers/type for reCAPTCHA and hCaptcha need to be handled a bit differently. They are single integrations where the user can select a version within it. You'll need to sniff out which version they chose for it, e.g. `reCAPTCHA (v2 Invisible)`
<img width="361" alt="Screenshot 2023-12-14 at 8 06 10 AM" src="https://github.com/solspace/craft-freeform/assets/1821674/2a986f35-0f9e-4b66-abf0-182e58bdb0c9">

2023-12-14 14:18 UTC, kjmartens commented on packages/plugin/src/Services/DiagnosticsService.php
> +            $plural = 1 != $count ? 's' : '';
@gustavs-gutmanis true, but I am also a sucker for good pluralization 😅

2023-12-14 15:53 UTC, gustavs-gutmanis commented
@kjmartens why wouldn't we show the suggestion along with the error?
They might opt to increase it to 512M rather than just 256M

2023-12-14 16:08 UTC, gustavs-gutmanis commented on packages/plugin/src/Services/DiagnosticsService.php
> +                            };
Gorgeous! 👌🏻

2023-12-14 16:08 UTC, gustavs-gutmanis approved these changes

2023-12-14 17:09 UTC, kjmartens commented
> @kjmartens why wouldn't we show the suggestion along with the error? They might opt to increase it to 512M rather than just 256M

@gustavs-gutmanis True... perhaps I could just change the wording for the warning, because otherwise it looks a little clumsy with both notices showing. 🙂

2023-12-15 15:22 UTC, kjmartens approved these changes

2023-12-15 15:23 UTC, merged