[SFT-604] Add Created and Updated users
solspace/craft3-freeform pull request #942
Opened 2023-12-19 11:46 UTC by aaronlinley

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/form-settings/settings.sidebar.tsx
> +  }
Seems like none of the settings will be rendered until this is fetched.
I think it's better to show the settings with the loader and display this after it's loaded.

Also this would be a good candidate for its own component which handles fetching and rendering inside itself.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/form-settings/settings.sidebar.tsx
> +            Created by <SidebarMetaUserLink href="#">Admin</SidebarMetaUserLink> at:<br/> { ownership.created.datetime }
We will need to translate these values.
There's a `translate()` function used throughout the project, and it allows for placeholder replacement.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/client/src/app/pages/forms/edit/builder/tabs/form-settings/settings.sidebar.tsx
> +import {useQueryFormOwnership, useQueryFormSettings} from '@ff-client/queries/forms';
Be sure to either set your IDE to run lint or prettier automatically, or run the `npm run lint:fix` command. It should automatically format all your changes based on the eslint rules.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/client/src/types/forms.ts
> +    user: {};
I'm guessing `user` is going to be an ID and a name, so an object of 
```ts
{
  id: number;
  name: string;
}
```

Also both `created` and `updated` are of identical types, so we could define a single type before these, without exporting it, and have these two reuse it.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/plugin/src/controllers/api/FormsController.php
> +    public function actionOwnership(int $id): Response
When you open up the form builder for a specific form, it loads a serialized `Form` object from `admin/freeform/api/forms/[id]`.
Since you are adding two getter methods for `createdBy` and `updatedBy`, they should also be included in the serialization.

Please check the response from the endpoint, it might be that you already have this data fetched along with the form by default.

This is quite a small dataset which would benefit from being loaded with the rest of form settings, since each request prolongs the time in which the builder loads.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/plugin/src/migrations/m231219_105754_AddUsersToFormsTable.php
> +            'createdId',
`createdId` does not really portray what the ID stands for, could you please name it as `createdByUserId` and `updatedByUserId` instead, please?

Also, please update the references to these throughout the code as well.

2023-12-19 12:03 UTC, gustavs-gutmanis commented on packages/plugin/src/migrations/m231219_105754_AddUsersToFormsTable.php
> +class m231219_105754_AddUsersToFormsTable extends Migration
Because of how Craft CMS is built, it's not enough to make a migration, you also need to clone this very same thing inside the `Install.php` migration as well.

I know... it's not optimal, but it is what it is.

2024-01-04 17:44 UTC, kjmartens requested changes
Looks really good. I tested upgrade as well as fresh install. Behavior seems correct. One improvement, however, would be to remove the link to other users if they don't have the `Edit → Edit users` Craft permission. Currently it just links to `#` which isn't the greatest. 🙂

2024-01-04 17:44 UTC, kjmartens commented on packages/client/src/app/pages/forms/edit/builder/tabs/form-settings/settings.ownership.tsx
> +	console.log(ownership);
Just noting that the console log should be removed.

2024-01-05 09:50 UTC, gustavs-gutmanis requested changes
Stellar!
Just two more small updates and we're all set here.

2024-01-05 09:50 UTC, gustavs-gutmanis commented on packages/plugin/src/Bundles/Transformers/Builder/Form/FormTransformer.php
> +        $updatedByUserUrl = "#";
These need to be null if no users present

2024-01-05 09:50 UTC, gustavs-gutmanis commented on packages/plugin/src/Bundles/Transformers/Builder/Form/FormTransformer.php
> +                'datetime' => $form->getDateCreated()->format('n/j/Y, g:i A')
I would suggest sending a unix timestamp and using `date-fns` in react to format the date using local time formatting options instead.

2024-01-05 17:34 UTC, aaronlinley commented
@gustavs-gutmanis @kjmartens All PR feedback has now been addressed

2024-01-05 17:51 UTC, kjmartens approved these changes
Looks good to me 👌

2024-01-05 18:06 UTC, kjmartens requested changes
One issue I noticed is that the time is not correctly localized to me. I am `GTM-06` and it's currently `12:00` here, but the time saved is showing `01/05/2024, 6:00 PM`. When I change my timezone to other ones, it changes with it, but they are wrong too. Is it possible the timezone offset is "backwards" or something?

Also, should the date and time formatting not respect the Craft localization? For example, if I switch my language to `Russian`, it shows up the same (with `am`/`pm` etc), but in Craft Entries it switches to `05.01.2024, 13:09`. It isn't a massive deal, but my assumption was that with the recent changes you made, this was the intention? 🙂

2024-01-08 10:03 UTC, aaronlinley commented
Yeah, I can see some issues with the localization. It's not quite working the way I thought it would when using the `date-fns` formatting that @gustavs-gutmanis mentioned. I need to look into it a little further

2024-01-08 16:57 UTC, kjmartens commented
> Yeah, I can see some issues with the localization. It's not quite working the way I thought it would when using the `date-fns` formatting that @gustavs-gutmanis mentioned. I need to look into it a little further

@gustavs-gutmanis can you meet with @aaronlinley to let him know which adjustments are necessary to resolve this? 🙂

2024-01-09 14:00 UTC, gustavs-gutmanis commented
I can see `date-fns` doesn't deal with timezones. If you want timezones, we must install the `date-fns-tz` package, but even that won't solve this, because it doesn't infer the timezone from the browser, like Date does.

You could try using the [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to achieve this.

Or as an alternative - use Craft's date localization methods to send a parsed date string from the server already.

2024-01-09 16:27 UTC, aaronlinley commented
@kjmartens @gustavs-gutmanis I've updated the datetime handling to be more reliable now. It sends a ISO string from the server to the frontend, and uses `date-fns-tz` to format it in the current user's timezone. This displays the date correctly in the current timezone, and updates the value when the timezone is changed via Craft settings (e.g. GMT+1 displays the time as 1 hour earlier than GMT).

2024-01-09 17:13 UTC, kjmartens requested changes
Hmm, I am still seeing no difference.

- Times are still +6hrs ahead for me (e.g. should say 11:00am for me, but says 5:00pm). My timezone is GMT-6.
- When I switch to a European locale for my user, dates/times are not formatted any differently (e.g. uses 12hr clock instead of 24hr clock).
- I am getting a new issue... about 30% of the time, a manual page refresh in the builder doesn't show the builder and console logs the following errors:

```
vendor.js?v=1704819269:2 TypeError: Cannot read properties of undefined (reading 'created')
    at t.SettingsOwnership (client.js?v=1704819269:1:259266)

vendor.js?v=1704819269:2 Uncaught TypeError: Cannot read properties of undefined (reading 'created')
    at t.SettingsOwnership (client.js?v=1704819269:1:259266)
```

The part of the JS file it refers to is:
`c.utcToZonedTime)(new Date(e.created.datetime), t)`

2024-01-11 12:13 UTC, gustavs-gutmanis approved these changes
Looking good! 👍🏻

2024-01-11 17:01 UTC, kjmartens approved these changes
Wonderful

2024-01-11 17:01 UTC, merged